### ISSUE TITLE
a response for your question in stackoverflow

### ISSUE THREAD

**Issue by hadirezaei1377** [psankar/static-serve#1]
change the main.go content to this :
package main

import (
	"embed"
	"io/fs"
	"log"
	"net/http"
)

//go:embed public
var public embed.FS

func main() {
	publicFS, err := fs.Sub(public, "public")
	if err != nil {
		log.Fatal(err)
	}
	
	http.Handle("/embedded/", http.StripPrefix("/embedded/",
		http.FileServer(http.FS(publicFS))))

	http.Handle("/public/",
		http.StripPrefix("/public/", http.FileServer(http.FS(public))))

	log.Fatal(http.ListenAndServe(":8080", nil))
}    it works on my local machine... I dont see 404 not found.

**Comment by psankar** [comment]
The issue is unrelated to the `StripPrefix`. The issue is because of the extra space in the go embed tag, i.e., `// go:embed` vs `//go:embed`. I just fixed it locally a few minutes back. Shall push the solution.

**Comment by psankar** [comment]
@hadirezaei1377 Can you update your stackoverflow answer highlighting the extra space between comment and the go:embed tag ? I will accept it. Thanks.
